### ISSUE TITLE
help with a project

### ISSUE THREAD

**Issue by xoceunder** [rokucommunity/sample-projects#5]
this my proyect

https://github.com/xoceunder/RokuDev

I want to make the entry of the GridScreen section load faster so that it loads the individual categories

@TwitchBronBron @chrisdp

**Comment by TwitchBronBron** [comment]
This project isn't really the place to ask these types of questions. You should join the Roku Community slack and ask future questions there ([here's an invite link](https://join.slack.com/t/rokudevelopers/shared_invite/zt-4vw7rg6v-NH46oY7hTktpRIBM_zGvwA))

You're rendering 12,869 unique grid cells! The way to speed that up is...render less. No user will realistically scroll through 11,366 comedy movies in a single row. Cap your rows at maybe 50-100 each. If you really need to display all of them, consider adding a "view all" tile at the end that takes you to a different page that shows a whole category in a new grid.

This change caps each category at 50, which makes the grid render almost instantly.
![image](https://user-images.githubusercontent.com/2544493/185395509-374d66fb-5ee7-4065-96bd-fc85b1161f23.png)

**Comment by xoceunder** [comment]
And how can I then load all the content of each category
@TwitchBronBron

**Comment by TwitchBronBron** [comment]
One option is to filter the list to 25 items from each category, with a 26th item being a button saying "view all" which would take you to a separate screen just for that category where you would show all the items in that one category.
